[package]
name = "rlox"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
phf = { version = "0.11", features = ["macros"] }

[profile.release]
lto = true
